// GET EMPLOYEE
export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_FAILED = "GET_EMPLOYEE_FAILED";

// POST EMPLOYEE
export const POST_EMPLOYEE_REQUEST = "POST_EMPLOYEE_REQUEST";
export const POST_EMPLOYEE_SUCCESS = "POST_EMPLOYEE_SUCCESS";
export const POST_EMPLOYEE_FAILED = "POST_EMPLOYEE_FAILED";
